name: Deploy Datasette

on:
  push:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '10 */6 * * *'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.1'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Deploy to Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        curl https://cli-assets.heroku.com/install.sh | sh
        python build_database.py apc/outages.db
        heroku plugins:install heroku-builds
        datasette publish heroku --name=apc-outages --install=datasette-cluster-map --install=datasette-vega apc/outages.db
