name: Selenium summary
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Prepare Selenium
       # https://github.com/marketplace/actions/setup-chromedriver
      uses: nanasess/setup-chromedriver@master    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements2.txt
    - name: Start XVFB
      run: |
        sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional, disables headless mode
    - name: Run app
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DISPLAY: :99
      run: |
        python apc/summary_scraper.py
        
    - name: commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git commit -m "update data" -a
        #git add --all
        #git commit -am "Latest data: $(date)"
        #git push origin main
      #env:
      #  REPO_KEY: ${{secrets.GITHUB_TOKEN}}
      #  username: github-actions

    - name: push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
